name: docker-spa
  # You may pin to the exact commit or the version.
  # uses: nexys-system/gh-actions-docker-spa@44a5a29252a259b5c2db0d8204f84bafe62d80cb
  uses: nexys-system/gh-actions-docker-spa@v0.0.23
  with:
    # github token
    githubtoken: # optional, default is ${{ github.token }}
    # docker port token
    port: # optional, default is 3000
    # path to dist/build folder
    distFolder: # optional, default is dist
    # node version
    nodeversion: # optional, default is 18
    # HTML entry point
    html-entry: # optional, default is index.html
    # name of the container
    container-name: # optional, default is ${{ github.event.repository.name }}
    # build command
    build-command: # optional, default is VITE_VERSION=${GITHUB_REF##*/} VITE_GIT_SHA=$GITHUB_SHA yarn build
    # The message to prepend the review suggestion
    message: # optional
